### ISSUE TITLE
Install Package not correct

### ISSUE THREAD

**Issue by EPTamminga** [sachatrauwaen/OpenImageProcessor#3]
evs.dnnsoftware.com check result:

* A file (\applicationhost.config) was found in the extension that was not included in manifest.
* A file (\resources.zip) was found in the extension that was not included in manifest.
* "Your extension has passed the Azure compatibility scan, however your manifest is missing the <azureCompatible>true</azureCompatible> tag."

**Comment by sachatrauwaen** [comment]
fixed in v 4.8.5
